{% set name = "morfeus-ml" %}
{% set version = "0.5.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/morfeus-ml-{{ version }}.tar.gz
  sha256: d63bc33e9da3214ddc874d46316adc9054ff8a771a7d4aa829efc0496738818c

build:
  number: 0
  noarch: python
  entry_points:
    - morfeus=morfeus.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - fire
    - numpy
    - python >=3.8
    - scipy

test:
  imports:
    - morfeus
  commands:
    - pip check
    - morfeus --help
  requires:
    - pip

about:
  home: https://github.com/kjelljorner/morfeus
  summary: A Python package for calculating molecular features
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kjelljorner
